name: example
description: A simple example of using supabase_schema_library.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.13.0

dependencies:
  supabase_schema:
    path: ../../supabase_schema
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

dev_dependencies:
  supabase_schema_generator:
    path: ../../supabase_schema_generator
  freezed: ^4.0.1
  json_serializable: ^6.14.0
  lints: ^3.0.0
  build_runner: ^2.16.1

dependency_overrides:
  supabase_schema:
    path: ../../supabase_schema
